Lab4/carshop/carshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('', RedirectView.as_view(url='shop/')),
    path('shop/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab4/carshop/shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('signup/', views.signup, name='signup'),
    path('orders/', views.OrdersListView.as_view(), name='orders')
]

Lab4/carshop/shop/models.py
from django.db import models
from django.urls import reverse

import uuid


class Product(models.Model):
    name = models.CharField(max_length=100)
    vendor_code = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class ProductInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this product")
    quantity = models.PositiveIntegerField(default=0)
    product = models.ForeignKey('Product', on_delete=models.RESTRICT, null=True)
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.SET_NULL, null=True)
    price = models.IntegerField(default=0)

    AVAILABLE_STATUS = (
        ('a', 'Available'),
        ('n', 'Not in stock'),
    )

    status = models.CharField(max_length=1, choices=AVAILABLE_STATUS, blank=True,
                              default='a', help_text='Product availability')

    class Meta:
        ordering = ['price', 'product']

    def __str__(self):
        return f'{self.id} ({self.product.name})'

    def get_absolute_url(self):
        return reverse('product_instance-detail', args=[str(self.id)])


class Manufacturer(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    products = models.ManyToManyField(Product)

    def get_absolute_url(self):
        return reverse('Supplier-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

    def display_products(self):
        return ', '.join(product.name for product in self.products.all()[:3])
    display_products.short_description = 'Products'


class Order(models.Model):
    quantity = models.PositiveIntegerField()
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)
    date_of_import = models.DateField(null=True, blank=True)
    unit_price = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        ordering = ['quantity']

    def __str__(self):
        return f"'{self.product}' ord: {self.date_of_import} - {self.quantity} units"

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

Lab4/carshop/shop/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import date


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'date_of_birth', 'phone', 'password1', 'password2')

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not re.match(r'^\+375 \d{2} \d{7}$', phone):
                raise forms.ValidationError("Phone number must be in the format +375 XX XXXXXXX.")
        return phone

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if date_of_birth:
            today = date.today()
            age = today.year - date_of_birth.year - (
                        (today.month, today.day) < (date_of_birth.month, date_of_birth.day))
            if age < 18:
                raise forms.ValidationError("You must be at least 18 years old to register.")
        return date_of_birth

    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={}))
    second_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={}))
    email = forms.CharField(widget=forms.EmailInput(attrs={}))
    date_of_birth = forms.DateField(label='Birth date', widget=forms.DateInput(attrs={'type': 'date'}))
    phone = forms.CharField(max_length=15, widget=forms.TextInput(attrs={
        'placeholder': '+375 XX XXXXXXX',
    }))
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={}))
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={}))

Lab4/carshop/shop/views.py
from django.shortcuts import render
from .models import Order, Product, ProductInstance, Manufacturer, Supplier
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from .forms import SignupForm


def index(request):
    num_products = Product.objects.all().count()
    num_instances = ProductInstance.objects.all().count()
    num_instances_available = ProductInstance.objects.filter(status__exact='a').count()
    num_manuf = Manufacturer.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={'num_products': num_products, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 'num_manuf': num_manuf, 'num_visits': num_visits},
    )


class ProductListView(generic.ListView):
    model = Product
    paginate_by = 10


class OrdersListView(LoginRequiredMixin, generic.ListView):
    login_url = 'login'
    model = Order
    paginate_by = 4


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = 'login'
    model = Product


def signup(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('login')
    else:
        form = SignupForm()

    context = {'form': form}
    return render(request, 'registration/signup.html', context,)

Lab4/carshop/shop/templates/base_generic.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">

    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0"></div>
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'index' %}" class="nav-link active" aria-current="page">Home</a></li>
            <li><a href="{% url 'products' %}" class="nav-link px-2">All products</a></li>
            <li><a href="{% url 'orders' %}" class="nav-link px-2">Orders</a></li>
            <li><a href="#" class="nav-link px-2">FAQs</a></li>
            <li><a href="#" class="nav-link px-2">About</a></li>
        </ul>


        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
            <li class="text-body-secondary">{{ user.get_username }}</li>

            <button type="button" class="btn btn-outline-primary me-2"
                    onclick="window.location.href='{% url 'logout'%}?next={{request.path}}'">Sign out
            </button>
            {% else %}
            <button type="button" class="btn btn-outline-primary me-2"
                    onclick="window.location.href='{% url 'login' %}?next={{request.path}}'">Sign in
            </button>
            <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'signup' %}'">Sign up
            </button>
            {% endif %}

        </div>

    </header>
</div>


{% block content %}{% endblock %}

{% block pagination %}
{% if is_paginated %}
<div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
</div>
{% endif %}
{% endblock %}

</body>
</html>

Lab4/carshop/shop/templates/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
<div style="text-align: center;">
    <h1>Auto shop Home</h1>

    <p>Welcome to <em>Auto shop</em>, a company that sells spare parts for cars.</p>

    <h2>Dynamic content</h2>

    <p>The library has the following record counts:</p>
    <ul style="display: inline-block; text-align: left;">
        <li><strong>Products:</strong> {{ num_products }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manuf }}</li>
        <li><strong>Visits:</strong>{{ num_visits }}</li>
    </ul>
</div>

{% endblock %}

Lab4/carshop/shop/templates/shop/order_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 style="font-size: 50px; margin-left: 30px;">Orders</h1>

{% if order_list %}
<ul>

    {% for order in order_list %}
    <hr>
    <a style="font-size: 30px;"><strong>Product: </strong> {{order.product.name}}   </a>
    <i style="font-size: 15px;"><strong>Manufacturer: </strong> {{order.manufacturer.name}}</i>
    <br>
    <a style="font-size: 20px;"><strong>Supplier: </strong> {{order.supplier.name}}</a>
    <br>
    <a style="font-size: 20px;"><strong>Date: </strong> {{order.date_of_import}}</a>
    <br>
    <a style="font-size: 25px;"><strong>Quantity: </strong> {{order.quantity}}  </a>
    <i style="font-size: 15px;"><strong>Unit price: </strong> {{order.unit_price}}</i>
    {% endfor %}

</ul>
{% else %}
<p>There are no products.</p>
{% endif %}
{% endblock %}

Lab4/carshop/shop/templates/shop/product_detail.html
{% extends "base_generic.html" %}

{% block content %}

  <a href="{% url 'products' %}" style="margin-left: 30px;"><--Back</a>


  <h1 style="font-size: 50px; margin-left: 30px; margin-top: 10px;">{{ product.name }}</h1>

  <p style="font-size: 18px; margin-left: 35px;"><strong>Vendor code: {{ product.vendor_code }}</strong></p>


  <div style="margin-left:50px;margin-top:20px">
    <h4>All Products</h4>

    {% for copy in product.productinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% else %}text-danger{% endif %}">{{ copy.get_status_display }}</p>
    <p><strong>In stock: </strong> {{copy.quantity}}</p>
    <p><strong>Price: </strong> {{copy.price}}</p>
    <p><strong>Manufacturer: </strong> {{copy.manufacturer.name}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

Lab4/carshop/shop/templates/shop/product_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 style="font-size: 50px; margin-left: 30px;">Product List</h1>

    {% if product_list %}
    <ul>

      {% for product in product_list %}
      <li style="font-size: 20px; margin-left: 30px;">
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no products.</p>
    {% endif %}
{% endblock %}